apiVersion: v1
kind: List
items:

# Technically a service is not required since we are exposing the required
# container ports with hostPort directive but as for
# https://github.com/kubernetes/kubernetes/issues/23920
# this is a workaround to get the firewall properly configured
- apiVersion: v1
  kind: Service
  metadata:
    name: node-service
  spec:
    selector:
      name: node-ds
    ports:
      - name: node-logger
        port: 514
        protocol: TCP
        targetPort: 514
      - name: vdsm-kube
        port: 54321
        protocol: TCP
        targetPort: 54321
      - name: vdsm-ssh
        port: 22222
        protocol: TCP
        targetPort: 22
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: node-claim
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
    name: node-ds
  spec:
    paused: true
    template:
      metadata:
        labels:
          name: node-template
      spec:
        restartPolicy: "Always"
        hostIPC: true
        serviceAccountName: privilegeduser
        containers:
          - image: docker.io/bronhaim/vdsm-kube-logger:latest
            name: node-logger
            imagePullPolicy: "IfNotPresent"
            ports:
              - containerPort: 514
                protocol: TCP
                hostPort: 514

          - image: docker.io/bronhaim/vdsm-kube:latest
            name: node
            ports:
              - containerPort: 54321
                protocol: TCP
                hostPort: 54321
              - containerPort: 22
                protocol: TCP
                hostPort: 22222
            imagePullPolicy: "IfNotPresent"
            securityContext:
              privileged: true
            volumeMounts:
              - name: sys-fs-cgroup
                mountPath: /sys/fs/cgroup
                readOnly: true
              - name: dev
                mountPath: /dev
              - name: boot
                mountPath: /boot
        volumes:
          - name: sys-fs-cgroup
            hostPath:
              path: /sys/fs/cgroup
          - name: dev
            hostPath:
              path: /dev
          - name: boot
            hostPath:
              path: /boot
          - name: node-persist-data
            persistentVolumeClaim:
              claimName: node-claim
